excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://hvanderdys.github.io
title: puppies, pencils & pictures
tagline: Seeing beauty in everyday life.
description: Heather van der Dys's Blog
paginate: 5
